#featureserve static+front end
Digitale-Gardermoen/Network-Configuration-Scheduler pull request #3
Opened 2018-10-04 23:02 UTC by hakash

Added feature for front-end with PoC ready working code, css and styles. Color codes should possibly be reworked later, but this variant is ready for functional demo.

2018-10-05 09:32 UTC, dotkim requested changes
CSS does not work in Chrome v.64 on windows.
Buttons are not centered and has borders.

2018-10-05 10:34 UTC, hakash commented
Fixed issues with CSS and added parameter for getting the correct room config from the GET-handler for roomconfig

2018-10-07 17:32 UTC, dotkim approved these changes

2018-10-08 08:03 UTC, Headwiki approved these changes

2018-10-08 08:04 UTC, merged